### ISSUE TITLE
An error occurred while loading `.emacs`

### ISSUE THREAD

**Issue by mgrojo** [brownts/dotemacs-ada#1]
I followed the instructions and I received this error:

```
⛔ Warning (initialization): An error occurred while loading ‘/home/mgr/.emacs’:

Symbol's function definition is void: which-key-mode

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the ‘--debug-init’ option to view a complete error backtrace.
```

Was this supposed to be run with `-q`? I'll follow the rest of the instructions in that way and report any further problem.

**Comment by brownts** [comment]
Did you run the following commands from the README?:
```shell
git clone https://github.com/brownts/dotemacs-ada ~/.emacs-ada.d
emacs --init-directory=~/.emacs-ada.d
```

I'm a bit confused because your error message is talking about "/home/mgr/.emacs", but if you follow the instructions you should be specifying the `~/.emacs-ada.d` directory.  Can you provide a list of commands you performed to get to this point?  I don't see that error when running the commands indicated above.

**Comment by mgrojo** [comment]
Yes, from my history:
```
 1998  git clone https://github.com/brownts/dotemacs-ada ~/.emacs-ada.d
 1999  emacs --init-directory=~/.emacs-ada.d
```
The final step did not work for me in either of the two ways:
```
 2016  emacs -q --init-directory=~/.emacs-ada.d src/gtkada-application.adb
 2017  emacs --init-directory=~/.emacs-ada.d src/gtkada-application.adb
```
The first one starts without errors, but it leaves the buffer in the Fundamental mode. The `ada-ts-mode` is not recognized.

The second one raised the error I mentioned and then the same effect as the first one.

I tried again after removing the offending line in my `.emacs`: `(which-key-mode t)`

Then I've got these errors:

```
⛔ Error (use-package): Failed to install ada-ts-mode: Symbol’s function definition is void: lsp
⛔ Error (use-package): Failed to install company: Symbol’s function definition is void: lsp
```

In case it matters, this is my Emacs version:
```
GNU Emacs 29.4 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.20,
 cairo version 1.16.0) of 2024-06-24
```
It is the snap version installed on Ubuntu 22.04.

Is `--init-directory` supposed to avoid processing `.emacs`? It doesn't seem on my case. But forcing it passing `-q` didn't help either, as you see. I'm confused too.

**Comment by brownts** [comment]
> ```shell
>  2016  emacs -q --init-directory=~/.emacs-ada.d src/gtkada-application.adb
>  2017  emacs --init-directory=~/.emacs-ada.d src/gtkada-application.adb
> ```
> 
> The first one starts without errors, but it leaves the buffer in the Fundamental mode. The `ada-ts-mode` is not recognized.

You definitely don't want to use `-q`, as that bypasses the init file completely.

> Is `--init-directory` supposed to avoid processing `.emacs`? It doesn't seem on my case. But forcing it passing `-q` didn't help either, as you see. I'm confused too.

In Emacs 29, you can specify an alternate init directory, so we point it at the repository just cloned.  It should not be reading your .emacs file.  It should be using ~/.emacs-ada.d/init.el instead.

Can you verify `user-emacs-directory` after starting Emacs:
```shell
C-h v user-emacs-directory RET
```

It should be pointing at "~/.emacs-ada.d".

**Comment by brownts** [comment]
I saw some weird behavior if I created a ~/.emacs file (i.e., "touch ~/.emacs") and then tried to run the above command.  Could you try renaming our .emacs (i.e. `mv ~/.emacs ~/.emacs.orig`) and then re-running the commands above.  It might be there is a bug in Emacs which has problems if trying to use `--init-directory` when ~/.emacs exists.

**Comment by mgrojo** [comment]
Yes, I was following that path.

Running just `emacs`, the `user-emacs-directory` is:
```
Its value is "~/.emacs.d/"
```

Starting with `--init-directory`
```
Its value is "/home/mgr/.emacs-ada.d/"
```

After moving away` ~/.emacs`, it started to install packages without errors and finally the file is open using your configuration.

Maybe it's by design, not a bug. I have both a `.emacs` file and a `.emacs.d` directory for anything installed or saved automatically by Emacs. The switch is probably only affecting the location of that directory, but my `.emacs` is still read. The strange thing is that Emacs doesn't seem to provide a `--init-file` switch to change that default behaviour of reading `.emacs` when it exists.

Now that it is working, I receive this error:
```
    1   0 error    l-d---b  Project Problems
```
Is that expected?

**Comment by mgrojo** [comment]
I also receive this when calling `C-x p c`
```
eval: Invalid function: "alr build -- -gnatef"
```

And regarding formating, even with this included in `src/gtkada.gpr`:

```ada
   package Pretty_Printer is
      for Default_Switches ("Ada") use ("--source-line-breaks");
   end Pretty_Printer;
```

it turns this:
```ada
   procedure Marsh_Gapplication_Files
     (Closure         : GClosure;
      Return_Value    : Glib.Values.GValue;
      N_Params        : Glib.Guint;
      Params          : Glib.Values.C_GValues;
      Invocation_Hint : System.Address; User_Data : System.Address)
```
into this:
```ada
   procedure Marsh_Gapplication_Files
     (Closure         : GClosure; Return_Value : Glib.Values.GValue;
      N_Params        : Glib.Guint; Params : Glib.Values.C_GValues;
      Invocation_Hint : System.Address; User_Data : System.Address)
```

What is then `--source-line-breaks` supposed to avoid?

**Comment by brownts** [comment]
> After moving away` ~/.emacs`, it started to install packages without errors and finally the file is open using your configuration.

Great!

> 
> Maybe it's by design, not a bug.
>

Possibly, I did find this [issue](https://debbugs.gnu.org/db/72/72294.html) which seemed to report something similar and apparently they determined it wasn't a bug.  I can't say that I quite understand it, but I guess that's how it's supposed to work.

> 
> Now that it is working, I receive this error:
> 
> ```
>     1   0 error    l-d---b  Project Problems
> ```
> 
> Is that expected?

That's usually an indication that the Language Server either couldn't find the project file or there was an error in the project file. 

I did find an error in the .dir-locals.el file.  It should have been the following:

```elisp
((ada-ts-mode . ((lsp-ada-project-file . "src/gtkada.gpr")
                 (eglot-workspace-configuration .
                  (:ada (:projectFile "src/gtkada.gpr")))))
 (nil . ((compile-command . "alr build -- -gnatef"))))
```

I do see the "Project Problems" on my side through, so let me debug that a bit more and get back to you.  If the Language Server can't process the project file, then it won't have processed the Pretty_Printer settings either.

**Comment by brownts** [comment]
Ok, I believe this is fixed, please give it another try.  The main issue was incorrect .dir-locals.el.  I also discovered what I believe to be a bug in Eglot, so the configuration in the .dir-locals.el for Eglot actually has to be marked as `ada-mode` instead of `ada-ts-mode`.  I'll file a bug report on that.  I also discovered an issue with the indentation amount not being set correctly for Eglot.  I'll get a fix out soon for `ada-ts-mode`.  The indentation amount when using `lsp-mode` should be correct though.

**Comment by mgrojo** [comment]
I'm still not able to make it work correctly. The error about the project is gone, but the effect is now worse.

The `lsp-mode` version does not navigate nor indent. It has this message in the modeline:
![imagen](https://github.com/user-attachments/assets/88f97b4b-7624-4005-af97-1d8814136551)

When I try to indent something, it says:
```
lsp--send-request-async: The connected server(s) does not support method textDocument/rangeFormatting.
To find out what capabilities support your server use ‘M-x lsp-describe-session’
and expand the capabilities section
```
And when using `M-.` it says:
```
lsp--send-request-async: The connected server(s) does not support method textDocument/definition.
To find out what capabilities support your server use ‘M-x lsp-describe-session’
and expand the capabilities section
```

Company only works after disabling and enabling it again in the buffer.

`ada_language_server` on path is:

```/home/mgr/.vscode/extensions/adacore.ada-24.0.6/x64/linux/ada_language_server```

What I see is that VS Code does not work either, with these settings:
```
{
    "ada.projectFile": "src/gtkada.gpr",
    "ada.defaultCharset": "utf-8",
    "ada.enableDiagnostics": false,
    "ada.renameInComments": false
 }
```

My entire `*Messages*` is:
```
Loading /home/mgr/.emacs-ada.d/custom-settings.el (source)...done
For information about GNU Emacs and the GNU system, type C-h C-a.
LSP :: Connected to [ada-ls:102150/starting /home/mgr/src/alire/gtkada_24.0.0_80c56171].
scroll-up-command: End of buffer [5 times]
<backtab> is undefined
goto-history-element: Beginning of history; no preceding item
Company mode disabled in current buffer
Company mode enabled in current buffer
Mark set [2 times]
lsp--send-request-async: The connected server(s) does not support method textDocument/rangeFormatting.
To find out what capabilities support your server use ‘M-x lsp-describe-session’
and expand the capabilities section
lsp--send-request-async: The connected server(s) does not support method textDocument/rangeFormatting.
To find out what capabilities support your server use ‘M-x lsp-describe-session’
and expand the capabilities section
Company mode disabled in current buffer
Company mode enabled in current buffer
minor-mode-menu-from-indicator: Cannot find minor mode for ‘ada-ls:102150/starting’
describe-minor-mode-from-indicator: Cannot find minor mode for ‘ada-ls:102150/starting’
Mark set
Saving file /home/mgr/src/alire/gtkada_24.0.0_80c56171/src/gtkada-application.adb...
Wrote /home/mgr/src/alire/gtkada_24.0.0_80c56171/src/gtkada-application.adb
Mark set
lsp--send-request-async: The connected server(s) does not support method textDocument/definition.
To find out what capabilities support your server use ‘M-x lsp-describe-session’
and expand the capabilities section
Beginning of buffer
Mark set [2 times]
lsp--send-request-async: The connected server(s) does not support method textDocument/definition.
To find out what capabilities support your server use ‘M-x lsp-describe-session’
and expand the capabilities section
```

Something seems to be broken, but I don't know why.

**Comment by brownts** [comment]
I have now fixed the Eglot indentation issue in `ada-ts-mode` and it is now available from MELPA.  I've also filed a bug report against Eglot for the issue with the major mode problem in the .dir-locals.el, which can be found [here](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=73280).

As far as your current issue, my initial thought is that the language server is not starting up (or is hanging during startup), based on the information in your log.  Also the fact that you can't get VSCode to work points to some other issue outside of Emacs.  I'm running Ubuntu 22.04 as well and I can  use the configuration you posted above without issue in VSCode.  Therefore, I'd recommend you resolve the issue with VSCode not working before revisiting Emacs, as that is probably easier to debug.

![Screenshot_2024-09-15_16-13-59](https://github.com/user-attachments/assets/fe089f2e-767c-47c1-9d21-b0c2db8b9e2a)

Some ideas to try might be:
- Check the communication log between VSCode and the Ada language server.
  - Select the OUTPUT tab in the bottom window, select "Ada Language Server" from the drop-down menu and look there to see the communication between them.
- Try reinstalling the Ada extension in VSCode.
- Enable tracing within the Ada Language Server to try and diagnose what's happening (see [here](https://github.com/AdaCore/ada_language_server/blob/master/doc/traces.md) for details).

**Comment by mgrojo** [comment]
It works now. It was locking, probably due to some trial where I terminated Emacs incorrectly. After a reboot, and a fix of an inadvertent edition of the project file, it is working fine.

Indentation is still broken, even with `--source-line-breaks`. For example, if I try to get this:
```ada
   procedure Marsh_Gapplication_Files
     (Closure         : GClosure; Return_Value : Glib.Values.GValue;
      N_Params        : Glib.Guint; Params : Glib.Values.C_GValues;
      Invocation_Hint : System.Address; User_Data : System.Address)
```
back into this:
```ada
   procedure Marsh_Gapplication_Files
     (Closure         : GClosure;
      Return_Value    : Glib.Values.GValue;
      N_Params        : Glib.Guint;
      Params          : Glib.Values.C_GValues;
      Invocation_Hint : System.Address;
      User_Data       : System.Address)
```
by inserting new-lines after every `;`, it works fine until the last `;`, where it inserts a syntax error:
```ada
   procedure Marsh_Gapplication_Files
     (Closure         : GClosure;
      Return_Value    : Glib.Values.GValue;
      N_Params        : Glib.Guint;
      Params          : Glib.Values.C_GValues;
      Invocation_Hint : System.Address;
      User_Data       : System.Address)dress)
```
It works fine under VS Code.

I'm happy in any case, because other features are working as fine as in VS Code. Thanks for your help!

**Comment by brownts** [comment]
I was able to reproduce the issue where you get the syntax error.  If you disable the "on-type formatting", this appears to fix it for me.  I'll update the configuration, but can you verify this fixes it for you?

```elisp
(setq lsp-enable-on-type-formatting nil)
```

After setting `lsp-enable-on-type-formatting` as above, restart the workspace and retry your above scenario (i.e., "C-c l w r" to restart the workspace).

**Comment by mgrojo** [comment]
Yes, I reproduced it again, and after following your instructions, it no longer happens.

**Comment by brownts** [comment]
I've updated init.el to disable the on-type formatting.  I've also reworked the .dir-locals.el a little bit.  I'm now specifying "nil" for the mode to work around the Eglot issue where it doesn't pick up the directory local settings under certain scenarios. 

I believe I've addressed all the concerns on this issue, but if I missed something, feel free to reopen it.
